package indexbg.pdoi.wsclient.edelivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4-jbossorg-1
 * 2018-08-08T16:25:35.234+03:00
 * Generated source version: 3.2.4-jbossorg-1
 *
 */
@WebServiceClient(name = "EDeliveryIntegrationService",
                  wsdlLocation = "https://edelivery.egov.bg/Services/EDeliveryIntegrationService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class EDeliveryIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "EDeliveryIntegrationService");
    public final static QName BasicHttpBindingIEDeliveryIntegrationService = new QName("http://tempuri.org/", "BasicHttpBinding_IEDeliveryIntegrationService");
    static {
        URL url = null;
        try {
            url = new URL("https://edelivery.egov.bg/Services/EDeliveryIntegrationService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EDeliveryIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://edelivery.egov.bg/Services/EDeliveryIntegrationService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EDeliveryIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EDeliveryIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDeliveryIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EDeliveryIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EDeliveryIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EDeliveryIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IEDeliveryIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEDeliveryIntegrationService")
    public IEDeliveryIntegrationService getBasicHttpBindingIEDeliveryIntegrationService() {
        return super.getPort(BasicHttpBindingIEDeliveryIntegrationService, IEDeliveryIntegrationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEDeliveryIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEDeliveryIntegrationService")
    public IEDeliveryIntegrationService getBasicHttpBindingIEDeliveryIntegrationService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEDeliveryIntegrationService, IEDeliveryIntegrationService.class, features);
    }

}
