package indexbg.pdoi.zaqvlenie.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-08-29T15:56:49.105+03:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "APIZaqvlenieService", 
                  wsdlLocation = "http://localhost:8080/PDoi/APIZaqvlenie?wsdl",
                  targetNamespace = "http://ws.zaqvlenie.pdoi.indexbg/") 
public class APIZaqvlenieService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.zaqvlenie.pdoi.indexbg/", "APIZaqvlenieService");
    public final static QName APIZaqvleniePort = new QName("http://ws.zaqvlenie.pdoi.indexbg/", "APIZaqvleniePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/PDoi/APIZaqvlenie?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(APIZaqvlenieService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/PDoi/APIZaqvlenie?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public APIZaqvlenieService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public APIZaqvlenieService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIZaqvlenieService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public APIZaqvlenieService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public APIZaqvlenieService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public APIZaqvlenieService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns APIZaqvlenie
     */
    @WebEndpoint(name = "APIZaqvleniePort")
    public APIZaqvlenie getAPIZaqvleniePort() {
        return super.getPort(APIZaqvleniePort, APIZaqvlenie.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIZaqvlenie
     */
    @WebEndpoint(name = "APIZaqvleniePort")
    public APIZaqvlenie getAPIZaqvleniePort(WebServiceFeature... features) {
        return super.getPort(APIZaqvleniePort, APIZaqvlenie.class, features);
    }

}
