
package indexbg.pdoi.zaqvlenie.wsclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-08-29T15:56:49.075+03:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "WSFault", targetNamespace = "http://ws.zaqvlenie.pdoi.indexbg/")
public class WSFault extends Exception {
    
    private java.lang.String wsFault;

    public WSFault() {
        super();
    }
    
    public WSFault(String message) {
        super(message);
    }
    
    public WSFault(String message, Throwable cause) {
        super(message, cause);
    }

    public WSFault(String message, java.lang.String wsFault) {
        super(message);
        this.wsFault = wsFault;
    }

    public WSFault(String message, java.lang.String wsFault, Throwable cause) {
        super(message, cause);
        this.wsFault = wsFault;
    }

    public java.lang.String getFaultInfo() {
        return this.wsFault;
    }
}
