package indexbg.pdoi.wsclient.admreg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4-jbossorg-1
 * 2018-07-25T17:27:44.293+03:00
 * Generated source version: 3.2.4-jbossorg-1
 *
 */
@WebServiceClient(name = "BatchInfoService",
                  wsdlLocation = "https://iisda.government.bg/Services/RAS/RAS.Integration.Host/BatchInfoService.svc?singleWsdl",
                  targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
public class BatchInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://iisda.government.bg/RAS/IntegrationServices", "BatchInfoService");
    public final static QName WSHttpBindingIBatchInfoService = new QName("http://iisda.government.bg/RAS/IntegrationServices", "WSHttpBinding_IBatchInfoService");
    static {
        URL url = null;
        try {
            url = new URL("https://iisda.government.bg/Services/RAS/RAS.Integration.Host/BatchInfoService.svc?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BatchInfoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://iisda.government.bg/Services/RAS/RAS.Integration.Host/BatchInfoService.svc?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public BatchInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BatchInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BatchInfoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BatchInfoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BatchInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IBatchInfoService
     */
    @WebEndpoint(name = "WSHttpBinding_IBatchInfoService")
    public IBatchInfoService getWSHttpBindingIBatchInfoService() {
        return super.getPort(WSHttpBindingIBatchInfoService, IBatchInfoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBatchInfoService
     */
    @WebEndpoint(name = "WSHttpBinding_IBatchInfoService")
    public IBatchInfoService getWSHttpBindingIBatchInfoService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIBatchInfoService, IBatchInfoService.class, features);
    }

}
