package indexbg.pdoi.wsclient.admreg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4-jbossorg-1
 * 2018-07-25T17:27:44.265+03:00
 * Generated source version: 3.2.4-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", name = "IBatchInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBatchInfoService {

    @WebMethod(operationName = "GetBatchDetailedInfo", action = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetBatchDetailedInfo")
    @Action(input = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetBatchDetailedInfo", output = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetBatchDetailedInfoResponse")
    @RequestWrapper(localName = "GetBatchDetailedInfo", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.GetBatchDetailedInfo")
    @ResponseWrapper(localName = "GetBatchDetailedInfoResponse", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.GetBatchDetailedInfoResponse")
    @WebResult(name = "GetBatchDetailedInfoResult", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
    public indexbg.pdoi.wsclient.admreg.ArrayOfBatchType getBatchDetailedInfo(
        @WebParam(name = "batchIdentificationNumber", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        indexbg.pdoi.wsclient.admreg.ArrayOfString batchIdentificationNumber,
        @WebParam(name = "dateAt", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        javax.xml.datatype.XMLGregorianCalendar dateAt,
        @WebParam(name = "versionIDAt", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.Long versionIDAt
    );

    @WebMethod(operationName = "SearchBatchVersions", action = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchVersions")
    @Action(input = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchVersions", output = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchVersionsResponse")
    @RequestWrapper(localName = "SearchBatchVersions", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.SearchBatchVersions")
    @ResponseWrapper(localName = "SearchBatchVersionsResponse", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.SearchBatchVersionsResponse")
    @WebResult(name = "SearchBatchVersionsResult", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
    public indexbg.pdoi.wsclient.admreg.ArrayOfVersionBatchInfoType searchBatchVersions(
        @WebParam(name = "batchIdentificationNumber", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.String batchIdentificationNumber,
        @WebParam(name = "fromDate", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetTerritorialAdmStructure", action = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetTerritorialAdmStructure")
    @Action(input = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetTerritorialAdmStructure", output = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/GetTerritorialAdmStructureResponse")
    @RequestWrapper(localName = "GetTerritorialAdmStructure", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.GetTerritorialAdmStructure")
    @ResponseWrapper(localName = "GetTerritorialAdmStructureResponse", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.GetTerritorialAdmStructureResponse")
    @WebResult(name = "GetTerritorialAdmStructureResult", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
    public indexbg.pdoi.wsclient.admreg.TerritorialAdmStructure getTerritorialAdmStructure(
        @WebParam(name = "uic", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.String uic
    );

    @WebMethod(operationName = "SearchBatchesIdentificationInfo", action = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchesIdentificationInfo")
    @Action(input = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchesIdentificationInfo", output = "http://iisda.government.bg/RAS/IntegrationServices/IBatchInfoService/SearchBatchesIdentificationInfoResponse")
    @RequestWrapper(localName = "SearchBatchesIdentificationInfo", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.SearchBatchesIdentificationInfo")
    @ResponseWrapper(localName = "SearchBatchesIdentificationInfoResponse", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices", className = "indexbg.pdoi.wsclient.admreg.SearchBatchesIdentificationInfoResponse")
    @WebResult(name = "SearchBatchesIdentificationInfoResult", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
    public indexbg.pdoi.wsclient.admreg.ArrayOfBatchIdentificationInfoType searchBatchesIdentificationInfo(
        @WebParam(name = "batchIdentificationNumber", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.String batchIdentificationNumber,
        @WebParam(name = "batchUIC", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.String batchUIC,
        @WebParam(name = "admStructureKind", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        indexbg.pdoi.wsclient.admreg.AdmStructureKindsEnum admStructureKind,
        @WebParam(name = "batchType", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        indexbg.pdoi.wsclient.admreg.BatchTypeEnum batchType,
        @WebParam(name = "status", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        indexbg.pdoi.wsclient.admreg.BatchStatusEnum status,
        @WebParam(name = "dateAt", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        javax.xml.datatype.XMLGregorianCalendar dateAt,
        @WebParam(name = "versionIDAt", targetNamespace = "http://iisda.government.bg/RAS/IntegrationServices")
        java.lang.Long versionIDAt
    );
}
